package o.f.o.com.shareofo.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import o.f.o.com.shareofo.db.model.BicycleData;

import o.f.o.com.shareofo.db.dao.BicycleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bicycleDaoConfig;

    private final BicycleDao bicycleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bicycleDaoConfig = daoConfigMap.get(BicycleDao.class).clone();
        bicycleDaoConfig.initIdentityScope(type);

        bicycleDao = new BicycleDao(bicycleDaoConfig, this);

        registerDao(BicycleData.class, bicycleDao);
    }
    
    public void clear() {
        bicycleDaoConfig.getIdentityScope().clear();
    }

    public BicycleDao getBicycleDao() {
        return bicycleDao;
    }

}
