// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ofo.proto at 15:1
package o.f.o.com.shareofo.net.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class OfoDate extends Message<OfoDate, OfoDate.Builder> {
  public static final ProtoAdapter<OfoDate> ADAPTER = new ProtoAdapter_OfoDate();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_CODE = "";

  public static final String DEFAULT_PASSWORD = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String code;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String password;

  public OfoDate(String code, String password) {
    this(code, password, ByteString.EMPTY);
  }

  public OfoDate(String code, String password, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.code = code;
    this.password = password;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.code = code;
    builder.password = password;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OfoDate)) return false;
    OfoDate o = (OfoDate) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(code, o.code)
        && Internal.equals(password, o.password);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (code != null ? code.hashCode() : 0);
      result = result * 37 + (password != null ? password.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (code != null) builder.append(", code=").append(code);
    if (password != null) builder.append(", password=").append(password);
    return builder.replace(0, 2, "OfoDate{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<OfoDate, Builder> {
    public String code;

    public String password;

    public Builder() {
    }

    public Builder code(String code) {
      this.code = code;
      return this;
    }

    public Builder password(String password) {
      this.password = password;
      return this;
    }

    @Override
    public OfoDate build() {
      return new OfoDate(code, password, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_OfoDate extends ProtoAdapter<OfoDate> {
    ProtoAdapter_OfoDate() {
      super(FieldEncoding.LENGTH_DELIMITED, OfoDate.class);
    }

    @Override
    public int encodedSize(OfoDate value) {
      return (value.code != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.code) : 0)
          + (value.password != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.password) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, OfoDate value) throws IOException {
      if (value.code != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.code);
      if (value.password != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.password);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public OfoDate decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.code(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.password(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public OfoDate redact(OfoDate value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
