// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ofo.proto at 21:1
package o.f.o.com.shareofo.net.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PullData extends Message<PullData, PullData.Builder> {
  public static final ProtoAdapter<PullData> ADAPTER = new ProtoAdapter_PullData();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_CURRENT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer current;

  public PullData(Integer current) {
    this(current, ByteString.EMPTY);
  }

  public PullData(Integer current, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.current = current;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.current = current;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PullData)) return false;
    PullData o = (PullData) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(current, o.current);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (current != null ? current.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (current != null) builder.append(", current=").append(current);
    return builder.replace(0, 2, "PullData{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PullData, Builder> {
    public Integer current;

    public Builder() {
    }

    public Builder current(Integer current) {
      this.current = current;
      return this;
    }

    @Override
    public PullData build() {
      return new PullData(current, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PullData extends ProtoAdapter<PullData> {
    ProtoAdapter_PullData() {
      super(FieldEncoding.LENGTH_DELIMITED, PullData.class);
    }

    @Override
    public int encodedSize(PullData value) {
      return (value.current != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.current) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PullData value) throws IOException {
      if (value.current != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.current);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PullData decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.current(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PullData redact(PullData value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
